package cashier;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import javax.swing.*;
import java.net.URL;
/**
 *
 * @author Os 10
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form Splashsc
     */
    public SplashScreen() {
        initComponents();
        
        // Set window to center of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        // Set application icon
        URL resource = this.getClass().getResource("/img/logo_app.png");
        if (resource == null) {
            System.err.println("Resource not found");
        } else {
            System.out.println("Resource found: " + resource.toExternalForm());
            Image iconApp = new ImageIcon(resource).getImage();
            this.setIconImage(iconApp);
        }
        
        String displayText = "<html>"
                + "<p>Cashier Alexandra adalah aplikasi yang</p>"
                + "<p>dirancang khusus untuk memudahkan</p>"
                + "<p>transaksi di toko Alexandria Book Store.</p>"
                + "<p>Dengan antarmuka yang intuitif, aplikasi</p>"
                + "<p>ini memungkinkan kasir untuk melakukan</p>"
                + "<p>transaksi dengan cepat dan akurat,</p>"
                + "<p>serta memastikan pengalaman belanja</p>"
                + "<p>yang menyenangkan bagi pelanggan.</p>";
        
        descriptionApp.setText(displayText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        poto = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingValue = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        descriptionApp = new javax.swing.JLabel();
        descriptionApp1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier Alexandria");
        setUndecorated(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        poto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_cashier.png"))); // NOI18N

        LoadingBar.setBackground(new java.awt.Color(40, 56, 69));

        LoadingValue.setBackground(new java.awt.Color(255, 255, 255));
        LoadingValue.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");

        LoadingLabel.setText("Loading..");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 56, 69));
        jLabel2.setText("Cashier Alexandria");

        descriptionApp.setText("Deskripsi App");

        descriptionApp1.setText("©  2020 - 2024 Alexandria");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionApp1)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(LoadingValue))
                            .addComponent(descriptionApp, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LoadingBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(LoadingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(poto)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(LoadingValue)
                .addGap(18, 18, 18)
                .addComponent(LoadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descriptionApp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionApp1)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     SplashScreen sp = new SplashScreen();
     sp.setVisible(true);
     
     
      try {
          
          for(int i=0;i<=100;i++){
              Thread.sleep(40);
              sp.LoadingValue.setText(i +"%");
              
              if(i==10){
                  sp.LoadingLabel.setText("Memulai aplikasi..");
              }
              if(i==20){
                  sp.LoadingLabel.setText("Memuat data yang dibutuhkan...");
              }
              if(i==30){
                  sp.LoadingLabel.setText("Mengumpulkan sumber data");
              }
              if(i==40){
                 sp.LoadingLabel.setText("Menginstalasi data");
              }
              if(i==50){
                  sp.LoadingLabel.setText("Koneksi ke database...");
              }
              if(i==70){
                  sp.LoadingLabel.setText("Sukses Mengkoneksi...");
              }
              if(i==80){
                  sp.LoadingLabel.setText("Menjalankan Cashier...");
              }
              sp.LoadingBar.setValue(i);
          }
      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e);
      }
        sp.setVisible(false);
        sp.dispose(); 
        new ABSframe().setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel descriptionApp;
    private javax.swing.JLabel descriptionApp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel poto;
    // End of variables declaration//GEN-END:variables
}
